'use strict';var Hf=function(a){this.WE="number"==typeof a?0<a?1:0>a?-1:null:null==a?null:a?-1:1};Hf.prototype.lV=function(a,b){var c=0,e=0,f=!1;a=se(a,b).split(we);for(b=0;b<a.length;b++){var g=a[b];ue.test(se(g,void 0))?(c++,e++):ve.test(g)?f=!0:te.test(se(g,void 0))?e++:xe.test(g)&&(f=!0)}return 0==e?f?1:0:.4<c/e?-1:1};Hf.prototype.HU=function(a,b){return this.W1(this.lV(a,b))};Hf.prototype.W1=function(a){return-1==(0==a?this.WE:a)?"rtl":"ltr"};
Hf.prototype.mark=function(){switch(this.WE){case 1:return"\u200e";case -1:return"\u200f";default:return""}};if("undefined"!=typeof angular){var If=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&If.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.ow=this.ko=null;a.dirForText=function(a){b.ko||(b.ko=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.ow||(b.ow=new Hf("rtl"==b.ko));return b.ow.HU(a||"")}}],compile:function(a,b){b=b.key;var c=null,e=document.createElement("amr");
b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&e.setAttribute("id","missing"));if(b){var f=chrome.i18n.getMessage(b+"_ph"),c=[];if(null!=f)for(c=f.split("\ue000"),f=0;f<c.length;++f)c[f]=c[f].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else e.setAttribute("r","nokey");c?e.innerHTML=c:(e.setAttribute("tl","false"),e.innerHTML=a.html());a.replaceWith(e)}}})};var Jf=/^[\w+/]+[=]{0,2}$/;var Kf=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||h,f=e.document,g;g=(g=(g=(e||h).document.querySelector("script[nonce]"))&&g.getAttribute("nonce"))&&Jf.test(g)?g:void 0;g&&(a.nonce=g);if("help"==a.flow){var k=ma("document.location.href",e);!a.helpCenterContext&&k&&(a.helpCenterContext=k.substring(0,1200));k=!0;if(b&&JSON&&JSON.stringify){var n=JSON.stringify(b);(k=1200>=n.length)&&(a.psdJson=n)}k||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||
"//www.google.com/tools/feedback";if(k=e.GOOGLE_FEEDBACK_START)k.apply(e,b);else{var e=c+"/load.js?",q;for(q in a)b=a[q],null!=b&&!ta(b)&&(e+=encodeURIComponent(q)+"="+encodeURIComponent(b)+"&");a=f.createElement("script");g&&a.setAttribute("nonce",g);a.src=e;f.body.appendChild(a)}};m("userfeedback.api.startFeedback",Kf,void 0);var Lf=function(){this.pF=this.qE=this.receiverVersion=this.modelName=this.mK=this.Zr=this.st=""};var Mf=chrome.i18n.getMessage("4163185390680253103"),Nf=chrome.i18n.getMessage("492097680647953484"),Of=chrome.i18n.getMessage("2575016469622936324"),Pf=chrome.i18n.getMessage("128276876460319075"),Qf=chrome.i18n.getMessage("3326722026796849289"),Rf=chrome.i18n.getMessage("1018984561488520517"),Sf=chrome.i18n.getMessage("8205999658352447129"),Tf=chrome.i18n.getMessage("5723583529370342957"),Uf=chrome.i18n.getMessage("1550904064710828958"),Vf=chrome.i18n.getMessage("5014364904504073524"),Wf=chrome.i18n.getMessage("2194670894476780934"),
Xf=chrome.i18n.getMessage("6614468912728530636"),Yf=chrome.i18n.getMessage("5910595154486533449"),Zf=chrome.i18n.getMessage("5363086287710390513"),$f=chrome.i18n.getMessage("244647017322945605"),ag=chrome.i18n.getMessage("5375576275991472719"),bg=chrome.i18n.getMessage("4592127349908255218"),cg=chrome.i18n.getMessage("843316808366399491"),dg=chrome.i18n.getMessage("5699813974548050528"),eg=chrome.i18n.getMessage("8515148417333877999"),fg=chrome.i18n.getMessage("1636686747687494376"),gg=chrome.i18n.getMessage("4148300086676792937"),
hg=chrome.i18n.getMessage("3219866268410307919"),ig=chrome.i18n.getMessage("9211708838274008657"),jg=chrome.i18n.getMessage("8706273405040403641"),kg=chrome.i18n.getMessage("4756056595565370923"),lg=chrome.i18n.getMessage("7876724262035435114"),mg=chrome.i18n.getMessage("5485620192329479690"),og=chrome.i18n.getMessage("6963873398546068901"),pg=chrome.i18n.getMessage("3567591856726172993"),qg=chrome.i18n.getMessage("3239956785410157548");var rg=function(a,b){var c=this;this.rF=b;this.s=a;this.s.top=a;this.OF=[];this.VC=!1;this.me=new Lf;this.dca();this.Xba();this.Yba();this.Zba();this.aca();this.zV=Ya();this.s.userEmail="";chrome.identity.getProfileUserInfo(function(a){c.s.userEmail=a.email;c.Xp()});this.s.yourAnswerText=qg;this.s.language=chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.s.requestLogsInProgress=!1};d=rg.prototype;
d.Xba=function(){this.OF=[{value:"Bug",desc:Mf},{value:"FeatureRequest",desc:Nf},{value:"MirroringQuality",desc:Of},{value:"Discovery",desc:Pf},{value:"Other",desc:Qf}];this.s.feedbackTypes=this.OF};d.tC=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new sg(c,arguments[c]));b.push(new sg(0,arguments[0]));return b};
d.dca=function(){this.s.videoSmoothnessRatings=this.tC(Wf,Rf,Sf,Tf,Uf,Vf);this.s.videoQualityRatings=this.tC(Wf,Xf,Yf,Zf,$f,ag);this.s.audioQualityRatings=this.tC(Wf,bg,cg,dg,eg,fg)};d.Yba=function(){this.s.includeFineLogs=!0;this.s.feedbackType="Bug";this.s.sendFeedback=this.H8.bind(this);this.s.cancel=this.eT.bind(this);this.s.attachLogsClick=this.TD.bind(this);this.s.viewLogs=this.Zda.bind(this)};
d.Zba=function(){this.s.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.vT.bind(this));this.s.sufficientFeedback=!1};d.aca=function(){this.s.$watch("attachLogs",this.TD.bind(this));this.s.attachLogs=!0};d.eT=function(){this.s.feedbackDescription&&!confirm(gg)||window.close()};
d.vT=function(){var a=this.s.feedbackType;this.s.sufficientFeedback="MirroringQuality"==a?this.s.videoSmoothness||this.s.videoQuality||this.s.audioQuality||this.s.comments:"Discovery"==a?this.s.visibleInSetup||this.s.comments:!!this.s.feedbackDescription};
d.H8=function(){if(this.s.sufficientFeedback){var a=this.s.feedbackType,b="";"MirroringQuality"==a?(this.s.videoSmoothness&&(b+="\nVideo Smoothness: "+this.s.videoSmoothness),this.s.videoQuality&&(b+="\nVideo Quality: "+this.s.videoQuality),this.s.audioQuality&&(b+="\nAudio: "+this.s.audioQuality),this.s.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.s.projectedContentUrl),this.s.comments&&(b+="\nComments: "+this.s.comments)):"Discovery"==a?(this.s.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.s.visibleInSetup),this.s.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.s.hasNetworkSoftware),this.s.networkDescription&&(b+="\nNetwork Description: "+this.s.networkDescription),this.s.comments&&(b+="\nComments: "+this.s.comments)):b=this.s.feedbackDescription;this.G8("Type: "+a+"\n\n"+b)}};
d.G8=function(a){this.s.sendDialogText=hg;this.s.okButton=pg;this.s.feedbackSent=!1;this.rF.show({locals:{Oma:this.s.feedbackSent,Ksa:this.s.sendDialogText,e3:this.s.okButton},scope:this.s,preserveScope:!0,bindToController:!0,template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.Gv});this.yM(a,Date.now())};d.yM=function(a,b){var c=Date.now();!this.s.requestLogsInProgress||5E3<c-b?this.VU(a):setTimeout(this.yM.bind(this),1E3,a,b)};
d.VU=function(a){var b=this,c=0,e=function(a,c,e){e?a(!0):(b.s.sendDialogText=kg,b.Xp(),c(Error("Failed to send")))},f=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new pe(function(){c++;return new Promise(function(c,k){var g=b.s.userEmail,q=b.me;c=e.bind(null,c,k);k=chrome.runtime.getManifest();Kf({productId:85561,bucket:f,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:k.default_locale,enableAnonymousFeedback:!g,report:{description:a},callback:c},
{version:k.version,description:k.description,user_email:g||"NA",logs:q.st||"NA",external_logs:q.Zr||"NA",device_model:q.modelName||"NA",receiver_version:q.receiverVersion||"NA",dash_report_url:q.mK||"NA",cast_device_counts:q.qE,dial_device_counts:q.pF})})},1E4,4)).zu(2).start().then(function(){b.s.sendDialogText=jg;b.s.feedbackSent=!0;b.Xp()},function(){b.s.sendDialogText=ig;b.s.feedbackSent=!0;b.Xp()})};
d.TD=function(){var a=this;this.me=new Lf;this.s.attachLogs&&(this.s.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Bf(this.zV,"retrieve_log_data"),function(b){a.s.requestLogsInProgress=!1;a.me.st=b.logs||"no extension";b.castStreamingLogs&&(a.me.mK=b.castStreamingLogs);b.castDeviceCounts&&(a.me.qE=b.castDeviceCounts);b.dialDeviceCounts&&(a.me.pF=b.dialDeviceCounts);if(b=b.device)if(b.model&&(a.me.modelName=b.model),b.version&&(a.me.receiverVersion=b.version),!a.VC){var c=Ya();a.VC=!0;a.me.Zr=
Ef(b.ip,c,a.x4.bind(a))}}))};
d.Zda=function(){this.s.logsHeader=lg;this.s.sendLogs=mg;this.s.fineLogsWarning=og;this.s.okButton=pg;this.rF.show({locals:{Cja:this.s.attachLogs,st:this.me.st,doa:this.s.includeFineLogs,Xoa:this.s.logsHeader,Lsa:this.s.sendLogs,Qma:this.s.fineLogsWarning,e3:this.s.okButton},scope:this.s,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.Gv})};
d.x4=function(a,b){this.VC=!1;this.me.Zr="error"==a?"":b;this.s.attachLogs||(this.me.Zr="");this.Xp()};d.Xp=function(){this.s.$$phase||this.s.$apply()};d.Gv=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};rg.prototype.Gv.$inject=["$scope","$mdDialog"];var sg=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",rg]);m("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.Tl?!0:!1},void 0);m("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0},void 0);m("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof Je)return Ke(a);if(a instanceof Me)return Ne(a);if(a instanceof Ge)return He(a);if(a instanceof De)return Ee(a);if(a instanceof Pe)return Qe(a);throw Error();},void 0);
m("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return Ne(b);if("resourceUrl"==a||"templateUrl"==a)return Ke(b);if("url"==a)return b instanceof Je?Ke(b):He(b);if("css"==a)return Ee(b);if("js"==a)return Qe(b);throw Error();},void 0);
